### ISSUE TITLE
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-python#15]

**Comment by frankrousseau** [comment]
Hello, can you give more details about this bug?

**Comment by vaibhavahuja** [comment]
I tested the code for all the available facets. Some of them show the JSON Decode Error. It is because, when the requests module attempts to go to the following pages, it fails to get a JSON object. 
for example
`places = openfoodfacts.facets.get_purchase_places()
`
will show a JSON Decode Error. 

Should I submit a PR, removing all the instances showing a JSON Error from the facets and README.md?

**Comment by frankrousseau** [comment]
Prior to submit the PR, can you tell us what is the content of the returned body? It may be an error message that could help us to better understand the problem.

**Comment by Anubhav-Bhargava** [comment]
@frankrousseau The error message is 

``` 
>>> places = openfoodfacts.facets.get_purchase_places()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/openfoodfacts/__init__.py", line 21, in func
    return utils.fetch(facet)['tags']
  File "/usr/local/lib/python2.7/dist-packages/openfoodfacts/utils.py", line 43, in fetch
    return response.json()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 826, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python2.7/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python2.7/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Also 


```
>>> codes = openfoodfacts.facets.get_packaging_codes()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'get_packaging_codes'
```

**Comment by Anubhav-Bhargava** [comment]
@frankrousseau These exist in the API, but it was referenced wrongly in the python code.
