### ISSUE TITLE
HISTORY_PRODUCT missing

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-python#19]
11-14 18:55:16.889 20401-20401/openfoodfacts.github.scrachx.openfood I/Choreographer: Skipped 36 frames!  The application may be doing too much work on its main thread.
11-14 18:55:17.445 20401-20401/openfoodfacts.github.scrachx.openfood E/SQLiteLog: (1) no such table: HISTORY_PRODUCT
11-14 18:55:17.446 20401-20401/openfoodfacts.github.scrachx.openfood D/AndroidRuntime: Shutting down VM
11-14 18:55:17.448 20401-20401/openfoodfacts.github.scrachx.openfood E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                       Process: openfoodfacts.github.scrachx.openfood, PID: 20401
                                                                                       android.database.sqlite.SQLiteException: no such table: HISTORY_PRODUCT (code 1): , while compiling: SELECT * FROM HISTORY_PRODUCT WHERE barcode = ?
                                                                                           at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                                                           at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
                                                                                           at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
                                                                                           at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                                                                                           at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
                                                                                           at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
                                                                                           at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
                                                                                           at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1318)
                                                                                           at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1165)
                                                                                           at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1036)
                                                                                           at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1242)
                                                                                           at com.orm.SugarRecord.find(SugarRecord.java:201)
                                                                                           at com.orm.SugarRecord.find(SugarRecord.java:187)
                                                                                           at openfoodfacts.github.scrachx.openfood.network.OpenFoodAPIClient$1.onResponse(OpenFoodAPIClient.java:109)
                                                                                           at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:66)
                                                                                           at android.os.Handler.handleCallback(Handler.java:751)
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                           at android.os.Looper.loop(Looper.java:154)
                                                                                           at android.app.ActivityThread.main(ActivityThread.java:6088)
                                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by teolemon** [comment]
Nougat - Moto G - Installed master

**Comment by teolemon** [comment]
Scan a product - Crash on Scan

**Comment by teolemon** [comment]
Seems to be an instant run issue. Closing. Thanks @herau
